export interface WebcamChannel {
  channel_id: string;
  name: string;
  region: string;
  country_code: string;
  lat: number;
  lon: number;
  youtube_video_id: string;
  youtube_live: boolean;
  relevance_tags: string[];
  priority: "high" | "medium" | "low";
}

export const GEOPOLITICAL_WEBCAM_CHANNELS: WebcamChannel[] = [
  {
    channel_id: "gaza_border_north",
    name: "Gaza Border North",
    region: "Middle East",
    country_code: "IL",
    lat: 31.57,
    lon: 34.52,
    youtube_video_id: "qM-J3n3W8vQ",
    youtube_live: true,
    relevance_tags: ["gaza", "border", "conflict", "hamas"],
    priority: "high",
  },
  {
    channel_id: "gaza_border_east",
    name: "Gaza Border East",
    region: "Middle East",
    country_code: "IL",
    lat: 31.48,
    lon: 34.59,
    youtube_video_id: "1R8HknGzJ4Q",
    youtube_live: true,
    relevance_tags: ["gaza", "border", "conflict"],
    priority: "high",
  },
  {
    channel_id: "ukraine_kharkiv",
    name: "Kharkiv Live",
    region: "Eastern Europe",
    country_code: "UA",
    lat: 49.99,
    lon: 36.23,
    youtube_video_id: "live",
    youtube_live: true,
    relevance_tags: ["ukraine", "war", "kharkiv", "russia"],
    priority: "high",
  },
  {
    channel_id: "ukraine_kyiv",
    name: "Kyiv Live",
    region: "Eastern Europe",
    country_code: "UA",
    lat: 50.45,
    lon: 30.52,
    youtube_video_id: "live",
    youtube_live: true,
    relevance_tags: ["ukraine", "war", "kyiv", "russia"],
    priority: "high",
  },
  {
    channel_id: "ukraine_odesa",
    name: "Odesa Port",
    region: "Eastern Europe",
    country_code: "UA",
    lat: 46.48,
    lon: 30.72,
    youtube_video_id: "live",
    youtube_live: true,
    relevance_tags: ["ukraine", "port", "black sea", "russia"],
    priority: "medium",
  },
  {
    channel_id: "ukraine_mariupol",
    name: "Mariupol Area",
    region: "Eastern Europe",
    country_code: "UA",
    lat: 47.1,
    lon: 37.54,
    youtube_video_id: "live",
    youtube_live: true,
    relevance_tags: ["ukraine", "war", "mariupol", "russia"],
    priority: "medium",
  },
  {
    channel_id: "syria_idlib",
    name: "Idlib Monitoring",
    region: "Middle East",
    country_code: "SY",
    lat: 35.93,
    lon: 36.34,
    youtube_video_id: "live",
    youtube_live: true,
    relevance_tags: ["syria", "idlib", "turkey", "conflict"],
    priority: "high",
  },
  {
    channel_id: "syria_aleppo",
    name: "Aleppo Live",
    region: "Middle East",
    country_code: "SY",
    lat: 36.2,
    lon: 37.16,
    youtube_video_id: "live",
    youtube_live: true,
    relevance_tags: ["syria", "aleppo", "war", "rebel"],
    priority: "medium",
  },
  {
    channel_id: "iraq_baghdad",
    name: "Baghdad Traffic",
    region: "Middle East",
    country_code: "IQ",
    lat: 33.31,
    lon: 44.37,
    youtube_video_id: "live",
    youtube_live: true,
    relevance_tags: ["iraq", "baghdad", "security"],
    priority: "low",
  },
  {
    channel_id: "korea_dmz",
    name: "DMZ North South",
    region: "East Asia",
    country_code: "KP",
    lat: 37.95,
    lon: 126.62,
    youtube_video_id: "live",
    youtube_live: true,
    relevance_tags: ["korea", "dmz", "nuclear", "tension"],
    priority: "high",
  },
  {
    channel_id: "india_ladakh",
    name: "Ladakh Border",
    region: "South Asia",
    country_code: "IN",
    lat: 34.83,
    lon: 77.58,
    youtube_video_id: "live",
    youtube_live: true,
    relevance_tags: ["india", "china", "border", "tension"],
    priority: "high",
  },
  {
    channel_id: "india_kashmir",
    name: "Kashmir Valley",
    region: "South Asia",
    country_code: "IN",
    lat: 34.12,
    lon: 74.79,
    youtube_video_id: "live",
    youtube_live: true,
    relevance_tags: ["india", "pakistan", "kashmir", "conflict"],
    priority: "medium",
  },
  {
    channel_id: "taiwan_strait",
    name: "Taiwan Strait Monitor",
    region: "East Asia",
    country_code: "TW",
    lat: 24.48,
    lon: 119.94,
    youtube_video_id: "live",
    youtube_live: true,
    relevance_tags: ["taiwan", "china", "straits", "military"],
    priority: "high",
  },
  {
    channel_id: "taiwan_klm",
    name: "Keelung Port",
    region: "East Asia",
    country_code: "TW",
    lat: 25.13,
    lon: 121.74,
    youtube_video_id: "live",
    youtube_live: true,
    relevance_tags: ["taiwan", "port", "china"],
    priority: "medium",
  },
  {
    channel_id: "south_china_sea",
    name: "South China Sea",
    region: "Maritime",
    country_code: "CN",
    lat: 16.73,
    lon: 113.52,
    youtube_video_id: "live",
    youtube_live: true,
    relevance_tags: ["china", "sea", "dispute", "military"],
    priority: "high",
  },
  {
    channel_id: "persian_gulf",
    name: "Strait of Hormuz",
    region: "Middle East",
    country_code: "IR",
    lat: 26.57,
    lon: 56.12,
    youtube_video_id: "live",
    youtube_live: true,
    relevance_tags: ["iran", "hormuz", "oil", "tanker"],
    priority: "high",
  },
  {
    channel_id: "red_sea",
    name: "Red Sea Passage",
    region: "Middle East",
    country_code: "YE",
    lat: 14.93,
    lon: 43.15,
    youtube_video_id: "live",
    youtube_live: true,
    relevance_tags: ["yemen", "red sea", "houthis", "shipping"],
    priority: "high",
  },
  {
    channel_id: "pakistan_quetta",
    name: "Quetta Security",
    region: "South Asia",
    country_code: "PK",
    lat: 30.18,
    lon: 66.99,
    youtube_video_id: "live",
    youtube_live: true,
    relevance_tags: ["pakistan", "quetta", "taliban", "security"],
    priority: "medium",
  },
  {
    channel_id: "afghanistan_kabul",
    name: "Kabul Monitoring",
    region: "Central Asia",
    country_code: "AF",
    lat: 34.53,
    lon: 69.17,
    youtube_video_id: "live",
    youtube_live: true,
    relevance_tags: ["afghanistan", "taliban", "kabul"],
    priority: "low",
  },
  {
    channel_id: "libya_sirte",
    name: "Sirte Coast",
    region: "North Africa",
    country_code: "LY",
    lat: 31.19,
    lon: 16.59,
    youtube_video_id: "live",
    youtube_live: true,
    relevance_tags: ["libya", "sirte", "conflict", "mercenary"],
    priority: "medium",
  },
  {
    channel_id: "somalia_mogadishu",
    name: "Mogadishu Port",
    region: "East Africa",
    country_code: "SO",
    lat: 2.04,
    lon: 45.34,
    youtube_video_id: "live",
    youtube_live: true,
    relevance_tags: ["somalia", "al shabaab", "terror"],
    priority: "medium",
  },
  {
    channel_id: "haiti_portauprince",
    name: "Port-au-Prince Live",
    region: "Caribbean",
    country_code: "HT",
    lat: 18.55,
    lon: -72.34,
    youtube_video_id: "live",
    youtube_live: true,
    relevance_tags: ["haiti", "gang", "crisis", "violence"],
    priority: "medium",
  },
  {
    channel_id: "colombia_bogota",
    name: "Bogotá Live",
    region: "South America",
    country_code: "CO",
    lat: 4.71,
    lon: -74.07,
    youtube_video_id: "live",
    youtube_live: true,
    relevance_tags: ["colombia", "war", "farc", "security"],
    priority: "low",
  },
];

export function getWebcamChannelsByRegion(region?: string): WebcamChannel[] {
  if (!region) return GEOPOLITICAL_WEBCAM_CHANNELS;
  return GEOPOLITICAL_WEBCAM_CHANNELS.filter((c) => c.region === region);
}

export function getWebcamChannelsByTag(tag: string): WebcamChannel[] {
  return GEOPOLITICAL_WEBCAM_CHANNELS.filter((c) =>
    c.relevance_tags.some((t) => t.includes(tag.toLowerCase())),
  );
}

export function getHighPriorityChannels(): WebcamChannel[] {
  return GEOPOLITICAL_WEBCAM_CHANNELS.filter((c) => c.priority === "high");
}
